# Site settings
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               🤖 botc.at 😺
tagline:             a catalogue of bots, allies, media and materials 

description: >       # this means to ignore newlines until "url:"
                     a catalogue of bots, allies, media and materials
url:                 http://botc.at
#baseurl:             /botDB
twitter_username:    botALLY

# Custom
theme:               theme-base-0d

# About/contact
author:
  name:              Tully Hansen
  url:               https://twitter.com/tullyhansen
  email:             tully@tullyhansen.com
  
github:
  repo:              https://github.com/tullyhansen/botcat

# Custom vars
version:             0.0

# Build settings
markdown: kramdown

exhibit_data_test:
  - https://spreadsheets.google.com/feeds/list/1JA6m8kky86NJaArUMs1KMLeIEFMtY_ZL9uuCV-30GTU/1/public/values?alt=json-in-script

exhibit_data_prod:
  - https://spreadsheets.google.com/feeds/list/1vleb6Y37ctkjlWbCiTemABgpit83eqW1FT8HEwc0l9I/1/public/values?alt=json-in-script
  - https://spreadsheets.google.com/feeds/list/1vleb6Y37ctkjlWbCiTemABgpit83eqW1FT8HEwc0l9I/2/public/values?alt=json-in-script
  
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"